# Generated by Django 4.2.7 on 2023-12-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.CharField(max_length=150, verbose_name='slug')),
                ('text', models.TextField(verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('is_published', models.BooleanField(default=True, verbose_name='is_published')),
                ('views_count', models.IntegerField(default=0, verbose_name='views_count')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
