# Generated by Django 4.2.7 on 2023-11-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='product_name')),
                ('product_description', models.TextField(verbose_name='product_description')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='product_image')),
                ('product_category', models.CharField(max_length=150, verbose_name='product_category')),
                ('product_price', models.IntegerField(verbose_name='product_price')),
                ('product_datetime_create', models.DateTimeField(blank=True, null=True, verbose_name='product_datetime_create')),
                ('product_datetime_change', models.DateTimeField(blank=True, null=True, verbose_name='product_datetime_change')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
