# Generated by Django 4.2.7 on 2024-01-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_is_published',
            field=models.BooleanField(default=False, verbose_name='product_is_published'),
        ),
    ]
